#syntax=ghcr.io/aica-technology/package-builder:v1.4.0

[metadata]
version = "0.2.0"
description = "Component package to S3C part detection"

[build]
type = "ros"
image = "v2.0.2-jazzy"

[build.dependencies]
"@aica/foss/control-libraries" = "v9.1.0"
"@aica/foss/modulo" = "v5.1.0"

[build.packages.pd]
source = "./src/s3c_part_detection"
